[fittersettings]
ExtremeChi2Cut = 1000

# List of fit parameters input to fitter
[fitparameters]

# Names of the class of fit parameters
names = [
    "norm",
    #"alpha",
    #"cathode",
    #"reflectivity",
    #"source",
    "scr",
]

norm = [
    "Norm", # Type of parameters
    1, # Number of parameters
    [
        ["Norm", 0.0174163, 0.001, 0, 100, true], # name, prefit, stepsize, min, max, fix
    ], # Vector of parameters
]

alpha = [
    "Attenuation", 
    1, 
    [
        ["alpha", 1E5, 1, 0, 1E10, false], 
    ], 
]

cathode = [
    "Cathode", 
    3, 
    [
        ["s1", 1.0, 0.01, 0.0, 10.0, false], 
        ["s2", 1.0, 0.01, 0.0, 10.0, false], 
        ["s3", 0.46, 0.01, 0.35, 0.6, true], 
    ], 
]

reflectivity = [
    "Reflectivity", 
    1, 
    [
        ["Reflectivity",  1, 0.1, 0, 10, false],
    ],
]

source = [
    "Source", 
    3, 
    [
        ["dTheta",  0, 1, 0, 10, false],
        ["dPhi",  0, 0.1, -3.14, 3.14, false],
        ["sigma", 15, 0.1, 10, 30, false], 
    ]
]

scr = [
    "SourceCathodeReflectivity", 
    6, 
    [
        ["dTheta",  0, 1, 0, 10, false],
        ["dPhi",  0, 0.1, -3.14, 3.14, false],
        ["sigma", 15, 0.1, 10, 30, false], 
        ["s1", 1, 0.01, 0.0, 10.0, false], 
        ["s2", 1, 0.01, 0.0, 10.0, false], 
        ["reflectivity",  1, 0.1, 0, 10, false],
    ]
]